### ISSUE TITLE
Some URLs are lost in the queue and not refreshed

### ISSUE THREAD

**Issue by molszowy** [lestrrat-go/httprc#6]
Hi!

Thanks for the work on this module. Really appreciate it.

I think I found a bug when trying to use [JWK auto-refresh](https://github.com/lestrrat-go/jwx/blob/v2/docs/04-jwk.md#auto-refreshing-remote-keys) which leverages this module.

When you register multiple URLs, each entry for respective URL should be enqueued  in `fetchLoop` however some legitimate entries are lost and effectively some URLs are not refreshed at all.

`slice` is mutable so [here](https://github.com/lestrrat-go/httprc/blob/main/queue.go#L350) the item is incorrectly inserted and the following code would help:

```
list = append(list[:i+1], list[i:]...)
list[i] = &rqentry{fireAt: fireAt, url: u}
```

Let me know what you think @lestrrat.

**Comment by lestrrat** [comment]
Oh, yeah, that looks like something that needs two steps instead of one.
Can you please create a PR that also contains a failing test ? Thanks!

**Comment by molszowy** [comment]
I didn't have time to get to this earlier. Thanks for the quick fix!

**Comment by lestrrat** [comment]
@molszowy no problem, thanks for the report!
